### ISSUE TITLE
BUG-000122962 When using the Crowdsource Reporter app to submit a report on iPhones, the drawn feature always disappears and users are unable to submit a report based on that location.

### ISSUE THREAD

**Issue by mariafroy** [Esri/crowdsource-reporter#430] opened 2019-05-31 13:55 UTC
Hi, 

I've come across an issue with my Crowdsource Reporter app in AGOL when drawing polylines. I've only been able to reproduce it using iPhone (tested on vers. 5-8/SE and X). The app uses background map and a hosted feature layer in wkid 25833 (UTM33). The hosted feature layer was originally created in AGOL, but later overwritten from ArcGIS Pro in order to get the UTM33-projection. 

**Steps to reproduce:**

1. Create a Crowdsource Reporter app w/ background map + hosted FL polylines in UTM 33 (wkid 25833)
2. Start drawing line in map view
3. Double-click line to finish - the colour of the line stays red and/or dissapears completely [device-dependent] _(expected behaviour is black)_
4. Press the report-button - receive error mesasge due to lack of location _(expected behaviour is successful reporting with the drawn line)_

**Devices**
I've encountered this issue on the following devices _(using Google Chrome DevTools)_:
- iPhone 5/SE
- iPhone 6/7/8
- iPhone 6/7/8 Plus
- iPhone X

On iPad and iPad Pro, the behaviour is different. On step (3), the line does dissapear but I am still able to send in a report (the line appears in green after that).

The app works as expected on Samsung, Nexus, Nokia and Pixel devices (and PC). I havent encountered any issues using a hosted point layer in the same application (with same projection and workflow).

Is there an issue with the Draw tool in the JS API perhaps? I've seen this bug (https://support.esri.com/en/bugs/nimbus/TklNMDk2NzQ3) that applies to earlier JS versions - which version does the Crowdsource Reporter currently use?

**Comment by allisonmuise** [comment] 2019-09-09 18:11
@mariafroy Thanks for letting us know about this issue. Reporter is using the current version of the API - we update it with every release of AGOL. Did you notice this issue with services in web mercator, or did the behavior only appear after republishing in UTM 33?  Could you share your app URL?

**Comment by mariafroy** [comment] 2019-09-10 10:41
@allisonmuise Hi Allison, I've been in touch with the ESRI team and they were able to reproduce the bug. See: https://support.esri.com/en/bugs/nimbus/QlVHLTAwMDEyMjk2Mg==

**Comment by LindsayThomas** [comment] 2019-09-10 13:42
@allisonmuise  BUG-000122962

**Comment by allisonmuise** [comment] 2019-09-10 15:05
<div><div><p><b>Steps to reproduce:</b></p>

<ol><li>Create a Crowdsource Reporter app with background map and hosted feature layer polylines or polygons</li><li>Open app on iPhone and continue as guest user.</li><li>Start drawing feature in map view</li><li>Double-click screen to finish - the feature disappears completely <i>(expected behavior is for feature to remain on the map)</i></li><li>Press the report-button - receive error message due to lack of location <i>(expected behavior is successful reporting with the drawn line)</i></li></ol>

<p> </p>

<p><b>Devices</b></p>

<ul><li>iPhone 5/SE - Chrome, Firefox and Safari</li><li>iPhone 6/7/8 - Chrome, Firefox and Safari</li><li>iPhone 6/7/8 Plus - Chrome and Firefox</li><li>iPhone X - Chrome and Firefox</li></ul>

<p> </p></div><div>
<span><b>Salesforce ID:</b> <a href="https://qamonitor/sftriage?sfid=BUG-000122962">BUG-000122962</a></span><br/>
<span><b>Salesforce Submitter:</b> Nikolas Dingus</span><br/>
<span><b>Salesforce Submit Date:</b> 6/11/2019 5:49 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Failure/Error</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Repro Data:</b> (n/a)</span><br/>
<span><b>Work Around:</b> <p>Using a desktop browser or an Android device does not return the error message. On these devices, the feature is successfully drawn and submitted. This behavior does not affect iPads, and it seems to be entirely dependent on iPhones.</p></span><br/>
<span><b>Product:</b> (n/a)</span><br/>
<span><b>Functional Category:</b> ArcGIS Online Application Templates</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> (n/a)</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> (n/a)</span><br/>
</div></div>

**Comment by aparveen** [comment] 2019-09-10 15:26
@CTLocalGovTeam Could you please investigate this issue and see if it possible to fix in 7.3. Thanks.

**Comment by aparveen** [comment] 2019-09-11 15:50
@ashishchoure I am able to repro it consistently in Chrome Browser's Iphone emulator and in Safari on an actual device (Iphone XR),  here is the app link https://stategovernment.maps.arcgis.com/apps/CrowdsourceReporter/index.html?appid=64d66350d9844ad1a55ce44aaedda8e2. Seems like it does not finish drawing on double tap in both polygon and line layers.

**Comment by ashishchoure** [comment] 2019-09-11 16:49
@aparveen

I am not able to reproduce the issue on ios devices. However, the issue is reproducible in chrome browser but that too not consistently.

I will look into it more and update you accordingly.

**Comment by aparveen** [comment] 2019-09-11 17:35
@ashishchoure I agree that we can repro in Chrome Emulator consistently, in actual device it works sometimes after I double tap several times.
Also see this issue with Basic Viewer template with editing tools and this sample app for JS API 3.29 https://developers.arcgis.com/javascript/3/samples/toolbar_draw/, it seems like coming from JS API and not specific to Reporter.

**Comment by allisonmuise** [comment] 2019-11-27 20:51
closing as this is being handled by the JS team

**Closed by allisonmuise** 2019-11-27 20:51 UTC
Labels: High
