### ISSUE TITLE
Layer list panel's UI elements and text is jumbled on submitting comments in Android tablets

### ISSUE THREAD

**Issue by skrishn** [Esri/crowdsource-reporter#129] opened 2015-09-02 23:25 UTC
Issue is noticed in Android Tablets - Samsung Galaxy Tab S running 5.0.2 and Samsung Galaxy Tab 2 with version 4.1.2.

Steps to repro
1. Open a reporter app
2. Click on  map - choose a layer
3. Select an issue
4. Click Comment
5. Enter a comment
6. Hit Submit
7. Notice the UI elements and text in the panel is jumbled

Refreshing the map fixes the issue sometimes.

* Issue not seen in 3.8 apps on production.

**Comment by allisonmuise** [comment] 2015-09-03 15:27
This display issue is not seen on iOS devices or Android phones.

**Comment by allisonmuise** [comment] 2015-09-03 15:28
@CTLocalGovTeam : Can you take a look and see if you can identify the source of this issue, and the level of effort to resolve it?

**Comment by CTLocalGovTeam** [comment] 2015-09-15 06:58
@allisonmuise 

We see this behavior on tabs when a large number of comments are present. The UI elements appear partially (horizontal lines) for a second and then each comment starts rendering correctly till all comments are shown. We observed this to take a couple of seconds for about 15 comments. However, we never had to refresh the map. 

Are you experiencing an issue that the comments are not shown at all, or only the horizontal lines are displayed ?

Can you please share a screenshot of the issue?

**Comment by allisonmuise** [comment] 2015-09-15 15:41
@skrishn : Can you attache a screenshot of the issue?

**Comment by skrishn** [comment] 2015-09-18 17:55
Issue is now only reproducible in Android Tablets - Samsung Galaxy Tab S running 5.0.2

![screenshot_2015-09-18-10-48-50](https://cloud.githubusercontent.com/assets/3836616/9966763/88521a6e-5df3-11e5-9fcc-1b253abe20e8.png)

**Comment by allisonmuise** [comment] 2015-09-18 19:55
@CTLocalGovTeam : this issue isn't related to the comments or horizontal lines specifically. As you can see above, large portions of the panel aren't drawing at all.

**Comment by CTLocalGovTeam** [comment] 2015-09-21 12:30
@allisonmuise 
We are able to repro this issue and are investigating.

**Comment by CTLocalGovTeam** [comment] 2015-09-30 16:17
@allisonmuise 
We haven't been able to provide a complete fix for this. The issue is related to android devices only. When the keyboard is opened, the browser also resizes and because of this the text/controls gets jumbled.

To resolve this issue we are hiding the details panel and again showing the same with some time interval to trigger the browser to refresh elements on screen. 

This works only when there are few comments already added. For issues that do not have comments added and with only a single field in the comments form, this issue still occurs. We are still investigating further trying to find a way to handle this case and will keep you updated on our findings.

**Closed** 2015-11-23 17:41 UTC
Labels: question
