### ISSUE TITLE
Add support for uploading videos as attachments when accessing from a Mobile Device.

### ISSUE THREAD

**Issue by chris-fox** [Esri/crowdsource-reporter#434] opened 2019-07-02 13:12 UTC
When accessing Crowdsource Reporter from a computer you can select "All Files" from the browser to attach a video. This option is not available when you access from a mobile device like an IPhone.

From Mike T.

"The app is configured to only accept `image` MIME types.  One can bypass this on a computer by choosing “All Files (*.*)”, but this option is not available on the iPhone.

I modified the app to accept additional MIME types—Mp4, WebM, & Ogg (only supported video formats in HTML5 according to w3schools)—by changing
"accept": "image/*"
to
"accept": "image/*,video/mp4,video/webm,video/ogg"
in four places.  I don’t know if it’s needed in all places, but it got me an experiment that works."

**Comment by ashishchoure** [comment] 2019-07-05 07:55
@aparveen

We can change the code to allow users to add video files. This way user will be allowed to upload the videos in desktop and mobile devices.

Reporter app shows the attached images and documents in the left panel. Here is the screenshot : 
![image](https://user-images.githubusercontent.com/5525972/60706704-aad2e680-9f27-11e9-8790-e3725d81d2d8.png)

As shown in the above screenshot, we can add a image to give user's the visual clue that the added file is video (First image in gallery section). Once user clicks on that image the video will be played in browser's new tab.

Please let us know your thoughts on this approach.

**Comment by aparveen** [comment] 2019-07-17 19:01
@chris-fox  is this solution works for you?

**Comment by chris-fox** [comment] 2019-07-17 19:04
@aparveen, that looks good. Not sure where that generic video image is coming from, we may just want to validate that this is the image we want to show, not sure if there is some Esri standard for this.

**Comment by aparveen** [comment] 2019-07-17 20:10
> @aparveen, that looks good. Not sure where that generic video image is coming from, we may just want to validate that this is the image we want to show, not sure if there is some Esri standard for this.

@chris-fox do you know anybody who can help me find out if there is any esri standard image for this?

**Comment by chris-fox** [comment] 2019-07-18 17:29
@aparveen, I would recommend submitting a workfront request with the design center to get this. You can provide the use case and if there is a standard they can provide or will give you a new image to use.

**Comment by ashishchoure** [comment] 2019-07-25 10:13
@aparveen 

We have added a video image which is inline with the attachment image (it is shown when documents file are attached). However, we  can easily change the image based on your feedback,

Here is the screenshot : 
![image](https://user-images.githubusercontent.com/5525972/61865406-cca10700-aef0-11e9-9656-3b1c5c8b1670.png)

**Comment by aparveen** [comment] 2019-07-25 13:37
@ashishchoure thank you for the information, we are working on a video image and I will send it to you when we are done.

**Comment by aparveen** [comment] 2019-07-25 16:56
@ashishchoure attached the image to use for video thumbnail
[GenericVideoThumbnail_MobileUpload.zip](https://github.com/Esri/crowdsource-reporter/files/3432559/GenericVideoThumbnail_MobileUpload.zip)

**Comment by ashishchoure** [comment] 2019-07-26 05:52
@aparveen 

We have added the image and here is the screenshot of the same : 
![image](https://user-images.githubusercontent.com/5525972/61928919-979bbf80-af97-11e9-9f92-4eede3bafd93.png)

**Comment by skrishn** [comment] 2019-07-30 20:12
@aziza

I have a few suggestion and found some issues as well

Suggestion:

1. When more than one video is added, it provide no information on the video as it has a common thumbnail. How about providing a way to add a tool tip when attaching the video that way users know the content on hover?

2. Error message is generic: 3 of 3 attachment(s) failed to upload. If unsupported video version or lengthy video is uploaded we can provide more information on the error message.

3. Once a report is submitted with multiple videos and attachments, the form shows the attachments with a 'X' button on each attachment which removes the attachments if clicked. The 'x' button can be grayed out while it is in the process of uploading the attachments. 
  
![xbutton](https://user-images.githubusercontent.com/3836616/62160975-11021d80-b2ca-11e9-90a7-6a7718a59644.PNG)


Issues:
1. Adding an attachment and if back button is clicked without submitting and returning the submit form shows the attachment. Canceling out the form removes the attachments. 

2. When form is submitted with multiple attachments and going back to reports list and returning to submit another report there is an error message with the failed to upload error message if there was any problem with the previous report's attachments. 

![image](https://user-images.githubusercontent.com/3836616/62161277-a6051680-b2ca-11e9-8dec-7e734dd1ec0f.png)

**Comment by aparveen** [comment] 2019-07-31 21:05
> Issues:
> 
> 1. Adding an attachment and if back button is clicked without submitting and returning the submit form shows the attachment. Canceling out the form removes the attachments.
@skrishn I believe this is as designed.
> 2. When form is submitted with multiple attachments and going back to reports list and returning to submit another report there is an error message with the failed to upload error message if there was any problem with the previous report's attachments.
> @ashishchoure is it possible to add an indicator to show the status of the loading?

**Comment by ashishchoure** [comment] 2019-08-02 06:33
@aparveen 

We are looking into this issue and we will get back to you at the earliest.

**Comment by aparveen** [comment] 2019-08-07 15:58
@ashishchoure for unsupported video format, reporter wouldn't allow users to browse unsupported format, right? Also I am assuming Reporter would support all formats that AGOL supports, right?

**Comment by ashishchoure** [comment] 2019-08-08 07:16
@aparveen 

- Currently we have added the HTML5 supported video formats. However, as per your suggestion we can easily add all the AGOL supported formats.
- We have found the supported attachments format list in the [ArcGIS Runtime](https://developers.arcgis.com/net/10-2/desktop/guide/work-with-feature-attachments.htm) documentation link.
- From this link we are planning to add following extension for supported video formats:
         `MOV, MP2, MP3, MP4, MPA, MPE, MPEG, MPG, MPV2
- Regarding filtering the unsupported video formats, the file input control handles this scenario and filters the content based on the provided formats.

Please let us know if this works for you.

**Comment by aparveen** [comment] 2019-08-08 13:59
> @aparveen
> 
> * Currently we have added the HTML5 supported video formats. However, as per your suggestion we can easily add all the AGOL supported formats.
> * We have found the supported attachments format list in the [ArcGIS Runtime](https://developers.arcgis.com/net/10-2/desktop/guide/work-with-feature-attachments.htm) documentation link.
> * From this link we are planning to add following extension for supported video formats:
>   `MOV, MP2, MP3, MP4, MPA, MPE, MPEG, MPG, MPV2
> * Regarding filtering the unsupported video formats, the file input control handles this scenario and filters the content based on the provided formats.
> 
> ![image](https://user-images.githubusercontent.com/5525972/62684073-7f875f80-b9dd-11e9-8332-5280d7129d0d.png)
> 
> Please let us know if this works for you.
> Also, could you please verify the list of supported video formats through AGOL team. This will make sure we are on same page and not missing on any key format.

This works for us. This format list seems to be correct, this is AGOL doc for the supported attachment format. https://doc.arcgis.com/en/arcgis-online/manage-data/work-with-tables.htm

**Comment by ashishchoure** [comment] 2019-08-09 11:54
@aparveen 

Thank you for the confirmation.
We will do the necessary changes and send you the pull request at the earliest.

**Comment by ashishchoure** [comment] 2019-08-21 14:20
@aparveen 

We have updated the code to show the loading indicator until all the attachments are being processed. This change will be delivered in upcoming code drop,

**Comment by aparveen** [comment] 2019-08-23 22:46
@ashishchoure , 

1. The custom file filter is not showing .mov files in the list, Only shows .mp4 and .mpg files.
2. If I upload .mov or .mpg file report it, go back, then comeback to the report and try to play the videos, it downloads instead of playing them.

Could you please take a look.

**Comment by ashishchoure** [comment] 2019-08-27 12:58
@aparveen 

1. Yes, for videos its should only show the supported formats which we have included. Here is the list of supported formats :
- MOV
- MP4,
- MPA
- MPE
- MPEG
- MPG
- MPV2
2. For images, we have added support for all the image files. This is existing implementation and we have not touched this while adding support for video files.

We have fixed the issue of **".mov"** file not showing up in the custom filter list and we are planning to deliver this fix tomorrow.

**Comment by allisonmuise** [comment] 2019-09-09 15:58
@aparveen Is there work remaining on this issue?

**Comment by aparveen** [comment] 2019-09-09 16:13
@allisonmuise No, I was waiting for finishing QA testing on this, it looks good so far and haven't find any other issue, if you want I can close this and if I find anything will reopen it.

**Comment by aparveen** [comment] 2019-09-17 21:33
@ashishchoure, I can't browse any videos from actual iPhone device, it only gives me option to upload images. Could you please check this issue?

**Comment by ashishchoure** [comment] 2019-09-18 13:50
@aparveen 

We are able to reproduce the issue at our end. 

As discussed,
- I think the best solution will be to not to filter the videos as we have done the for images.
- If any unsupported video is being uploaded and if the server fails, the application will show the error **"attachment(s) failed to upload"**.

We are testing this implementation and we will send you the pull request tomorrow.

**Comment by aparveen** [comment] 2019-09-18 18:34
> @aparveen
> 
> We are able to reproduce the issue at our end.
> 
> As discussed,
> 
> * I think the best solution will be to not to filter the videos as we have done the for images.
> * If any unsupported video is being uploaded and if the server fails, the application will show the error **"attachment(s) failed to upload"**.
> 
> We are testing this implementation and we will send you the pull request tomorrow.
@ashishchoure could you please make sure to test on iPhone, iPad in both Safari and Chrome please?

**Comment by aparveen** [comment] 2019-09-25 14:03
Verified in dev and qa.

**Closed by aparveen** 2019-09-25 14:03 UTC
Labels: Enhancement, High, Update Solutions Doc
